[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FourierFlows = "2aec4490-903f-5c70-9b11-9bed06a700e1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeophysicalFlows = "44ee3b1c-bc02-53fa-8355-8e347616e15e"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
